import jsPDF from "jspdf";

/** Download agent result as CSV */
export function downloadCSV(agentName: string, result: Record<string, any>) {
  const rows: string[][] = [["Section", "Label", "Detail", "Tag"]];

  if (result.summary) {
    rows.push(["Summary", result.summary, "", ""]);
  }

  (result.sections || []).forEach((sec: any) => {
    (sec.items || []).forEach((item: any) => {
      rows.push([sec.title, item.label, item.detail, item.tag || ""]);
    });
  });

  (result.timeline || []).forEach((t: any) => {
    rows.push(["Timeline", t.phase, t.focus, `${t.pct}%`]);
  });

  (result.risks || []).forEach((r: string, i: number) => {
    rows.push(["Risks", `Risk ${i + 1}`, r, ""]);
  });

  if (result.confidence) {
    rows.push(["Confidence", result.confidence.level, result.confidence.reason, `${result.confidence.score}%`]);
  }

  const csv = rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${agentName.replace(/\s+/g, "_")}_result.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

/* ─── Helpers ─── */

const BRAND_BLUE = "#3b5eff";
const DARK = "#1a1a2e";
const GRAY = "#6b7280";
const LIGHT_BG = "#f8f9fc";
const WHITE = "#ffffff";
const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 20;
const CONTENT_W = PAGE_W - MARGIN * 2;
const FOOTER_Y = PAGE_H - 12;

function hexToRGB(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [parseInt(h.substring(0, 2), 16), parseInt(h.substring(2, 4), 16), parseInt(h.substring(4, 6), 16)];
}

function addFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  doc.setDrawColor(...hexToRGB("#e5e7eb"));
  doc.line(MARGIN, FOOTER_Y - 4, PAGE_W - MARGIN, FOOTER_Y - 4);
  doc.setFontSize(7);
  doc.setTextColor(...hexToRGB(GRAY));
  doc.text("Generated by unfoldHR  •  www.unfoldhrai.com  •  Confidential", MARGIN, FOOTER_Y);
  doc.text(`${pageNum} / ${totalPages}`, PAGE_W - MARGIN, FOOTER_Y, { align: "right" });
}

function ensureSpace(doc: jsPDF, y: number, needed: number, pages: number[]): [number, number[]] {
  if (y + needed > FOOTER_Y - 10) {
    doc.addPage();
    pages.push(pages.length + 1);
    return [MARGIN + 5, pages];
  }
  return [y, pages];
}

function drawSectionHeading(doc: jsPDF, y: number, title: string, color: string): number {
  doc.setFillColor(...hexToRGB(color));
  doc.roundedRect(MARGIN, y, 3, 14, 1.5, 1.5, "F");
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...hexToRGB(DARK));
  doc.text(title, MARGIN + 8, y + 10);
  return y + 22;
}

function wrapText(doc: jsPDF, text: string, maxWidth: number): string[] {
  return doc.splitTextToSize(text, maxWidth) as string[];
}

function getPriorityColor(tag: string): string {
  const t = (tag || "").toLowerCase();
  if (t.includes("high") || t.includes("critical") || t.includes("red")) return "#ef4444";
  if (t.includes("medium") || t.includes("moderate") || t.includes("amber") || t.includes("yellow")) return "#f59e0b";
  if (t.includes("low") || t.includes("green") || t.includes("good")) return "#22c55e";
  return GRAY;
}

/** Download agent result as branded PDF using jsPDF */
export function downloadPDF(
  agentName: string,
  result: Record<string, any>,
  options?: { logoUrl?: string | null; primaryColor?: string }
) {
  const primary = options?.primaryColor || BRAND_BLUE;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let pages = [1];

  /* ═══════════════════ COVER PAGE ═══════════════════ */
  // Background
  doc.setFillColor(...hexToRGB(DARK));
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");

  // Accent bar at top
  doc.setFillColor(...hexToRGB(primary));
  doc.rect(0, 0, PAGE_W, 5, "F");

  // Logo
  let logoY = 70;
  if (options?.logoUrl) {
    try {
      doc.addImage(options.logoUrl, "PNG", MARGIN, 50, 50, 25);
      logoY = 85;
    } catch { /* skip logo on error */ }
  }

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(...hexToRGB(WHITE));
  const titleLines = wrapText(doc, `${agentName} Recommendation`, CONTENT_W);
  titleLines.forEach((line, i) => {
    doc.text(line, MARGIN, logoY + 20 + i * 14);
  });

  // Subtitle line
  const subtitleY = logoY + 20 + titleLines.length * 14 + 10;
  doc.setFillColor(...hexToRGB(primary));
  doc.rect(MARGIN, subtitleY, 40, 1, "F");

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...hexToRGB("#9ca3af"));
  doc.text(`Generated ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`, MARGIN, subtitleY + 12);

  if (result.contextLine) {
    doc.setFontSize(10);
    doc.text(result.contextLine, MARGIN, subtitleY + 22);
  }

  // Footer on cover
  doc.setFontSize(9);
  doc.setTextColor(...hexToRGB(primary));
  doc.text("Powered by unfoldHR AI", MARGIN, PAGE_H - 25);
  doc.setFontSize(7);
  doc.setTextColor(...hexToRGB("#6b7280"));
  doc.text("www.unfoldhrai.com  •  Confidential", MARGIN, PAGE_H - 18);

  /* ═══════════════════ CONTENT PAGES ═══════════════════ */
  doc.addPage();
  pages.push(2);
  let y = MARGIN + 5;

  // ── Executive Summary ──
  if (result.summary) {
    y = drawSectionHeading(doc, y, "Executive Summary", primary);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...hexToRGB("#374151"));
    const summaryLines = wrapText(doc, result.summary, CONTENT_W - 8);
    summaryLines.forEach(line => {
      [y, pages] = ensureSpace(doc, y, 6, pages);
      doc.text(line, MARGIN + 8, y);
      y += 5;
    });
    y += 8;
  }

  // ── Confidence Score ──
  if (result.confidence) {
    [y, pages] = ensureSpace(doc, y, 35, pages);
    y = drawSectionHeading(doc, y, "Confidence Score", primary);

    const score = result.confidence.score || 0;
    const confColor = score >= 75 ? "#22c55e" : score >= 60 ? "#f59e0b" : "#ef4444";

    // Score card
    doc.setFillColor(...hexToRGB(LIGHT_BG));
    doc.roundedRect(MARGIN + 8, y, CONTENT_W - 8, 28, 3, 3, "F");

    // Score number
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...hexToRGB(confColor));
    doc.text(`${score}%`, MARGIN + 16, y + 16);

    // Level
    doc.setFontSize(12);
    doc.setTextColor(...hexToRGB(DARK));
    doc.text(result.confidence.level || "", MARGIN + 42, y + 12);

    // Reason
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...hexToRGB(GRAY));
    const reasonLines = wrapText(doc, result.confidence.reason || "", CONTENT_W - 58);
    reasonLines.slice(0, 2).forEach((line, i) => {
      doc.text(line, MARGIN + 42, y + 19 + i * 4);
    });

    // Progress bar
    doc.setFillColor(...hexToRGB("#e5e7eb"));
    doc.roundedRect(MARGIN + 42, y + 23, 80, 2, 1, 1, "F");
    doc.setFillColor(...hexToRGB(confColor));
    doc.roundedRect(MARGIN + 42, y + 23, 80 * (score / 100), 2, 1, 1, "F");

    y += 38;
  }

  // ── Key Metrics (from sections) ──
  const sections = result.sections || [];
  if (sections.length > 0) {
    [y, pages] = ensureSpace(doc, y, 30, pages);
    y = drawSectionHeading(doc, y, "Key Metrics & Analysis", primary);

    sections.forEach((sec: any) => {
      [y, pages] = ensureSpace(doc, y, 20, pages);

      // Section sub-header
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...hexToRGB(primary));
      doc.text(sec.title, MARGIN + 8, y);
      y += 6;

      (sec.items || []).forEach((item: any) => {
        [y, pages] = ensureSpace(doc, y, 14, pages);

        // Metric row with background
        doc.setFillColor(...hexToRGB(LIGHT_BG));
        doc.roundedRect(MARGIN + 8, y - 3, CONTENT_W - 8, 10, 1.5, 1.5, "F");

        // Label
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...hexToRGB(DARK));
        doc.text(item.label, MARGIN + 12, y + 3);

        // Detail
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...hexToRGB("#374151"));
        const detailWidth = CONTENT_W - 80;
        const detailLines = wrapText(doc, item.detail, detailWidth > 0 ? detailWidth : 60);
        doc.text(detailLines[0] || "", MARGIN + 62, y + 3);

        // Tag badge
        if (item.tag) {
          const tagColor = getPriorityColor(item.tag);
          const tagX = PAGE_W - MARGIN - 22;
          doc.setFillColor(...hexToRGB(tagColor));
          doc.roundedRect(tagX, y - 1, 18, 6, 2, 2, "F");
          doc.setFontSize(6);
          doc.setFont("helvetica", "bold");
          doc.setTextColor(...hexToRGB(WHITE));
          doc.text(item.tag.toUpperCase(), tagX + 9, y + 3, { align: "center" });
        }

        y += 12;
      });
      y += 4;
    });
  }

  // ── Timeline ──
  if (result.timeline?.length) {
    [y, pages] = ensureSpace(doc, y, 25, pages);
    y = drawSectionHeading(doc, y, "Implementation Timeline", primary);

    result.timeline.forEach((t: any) => {
      [y, pages] = ensureSpace(doc, y, 16, pages);

      // Phase
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...hexToRGB(DARK));
      doc.text(t.phase, MARGIN + 8, y + 3);

      // Focus
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...hexToRGB("#374151"));
      doc.text(t.focus, MARGIN + 50, y + 3);

      // Progress bar
      const barX = PAGE_W - MARGIN - 45;
      doc.setFillColor(...hexToRGB("#e5e7eb"));
      doc.roundedRect(barX, y, 35, 4, 2, 2, "F");
      doc.setFillColor(...hexToRGB(primary));
      doc.roundedRect(barX, y, 35 * (t.pct / 100), 4, 2, 2, "F");

      // Percentage
      doc.setFontSize(7);
      doc.setTextColor(...hexToRGB(GRAY));
      doc.text(`${t.pct}%`, PAGE_W - MARGIN, y + 3, { align: "right" });

      y += 12;
    });
    y += 6;
  }

  // ── Risks & Mitigations ──
  if (result.risks?.length) {
    [y, pages] = ensureSpace(doc, y, 25, pages);
    y = drawSectionHeading(doc, y, "Risks & Mitigations", primary);

    result.risks.forEach((r: string) => {
      [y, pages] = ensureSpace(doc, y, 14, pages);

      // Warning icon circle
      doc.setFillColor(...hexToRGB("#fef3c7"));
      doc.circle(MARGIN + 12, y + 1, 3, "F");
      doc.setFontSize(8);
      doc.setTextColor(...hexToRGB("#d97706"));
      doc.text("!", MARGIN + 11.3, y + 3);

      // Risk text
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...hexToRGB("#374151"));
      const riskLines = wrapText(doc, r, CONTENT_W - 25);
      riskLines.forEach((line, i) => {
        doc.text(line, MARGIN + 20, y + 3 + i * 4.5);
      });
      y += Math.max(10, riskLines.length * 4.5 + 4);
    });
    y += 4;
  }

  /* ═══════════════════ FOOTER ON ALL PAGES ═══════════════════ */
  const totalPages = doc.getNumberOfPages();
  for (let i = 2; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i - 1, totalPages - 1);
  }

  /* ═══════════════════ SAVE ═══════════════════ */
  doc.save(`${agentName.replace(/\s+/g, "_")}_Recommendation.pdf`);
}
