import jsPDF from "jspdf";

/* ─── CSV Export (unchanged) ─── */
export function downloadCSV(agentName: string, result: Record<string, any>) {
  const rows: string[][] = [["Section", "Label", "Detail", "Tag"]];

  if (result.summary) {
    rows.push(["Summary", result.summary, "", ""]);
  }

  (result.sections || []).forEach((sec: any) => {
    (sec.items || []).forEach((item: any) => {
      rows.push([sec.title, item.label, item.detail, item.tag || ""]);
    });
  });

  (result.timeline || []).forEach((t: any) => {
    rows.push(["Timeline", t.phase, t.focus, `${t.pct}%`]);
  });

  (result.risks || []).forEach((r: string, i: number) => {
    rows.push(["Risks", `Risk ${i + 1}`, r, ""]);
  });

  if (result.confidence) {
    rows.push(["Confidence", result.confidence.level, result.confidence.reason, `${result.confidence.score}%`]);
  }

  const csv = rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${agentName.replace(/\s+/g, "_")}_result.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

/* ─── Branded PDF Export via jsPDF ─── */

type RGB = [number, number, number];
const BRAND_NAVY: RGB = [28, 35, 48];
const BRAND_BLUE: RGB = [43, 92, 230];
const BRAND_TEAL: RGB = [16, 185, 129];
const WHITE: RGB = [255, 255, 255];
const LIGHT_GRAY: RGB = [245, 245, 250];
const TEXT_PRIMARY: RGB = [30, 30, 40];
const TEXT_SECONDARY: RGB = [100, 100, 115];
const RISK_HIGH: RGB = [220, 38, 38];
const RISK_MEDIUM: RGB = [234, 179, 8];
const RISK_LOW: RGB = [34, 197, 94];

const PAGE_W = 210;
const PAGE_H = 297;
const M_LEFT = 24;
const M_RIGHT = 24;
const M_TOP = 28;
const CONTENT_W = PAGE_W - M_LEFT - M_RIGHT;
const FOOTER_Y = PAGE_H - 14;
const FOOTER_TEXT = "Generated by unfoldHR  •  www.unfoldhrai.com  •  Confidential";

function addFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  doc.setFontSize(7.5);
  doc.setTextColor(...TEXT_SECONDARY);
  doc.setFont("helvetica", "normal");
  // Left: branding
  doc.text(FOOTER_TEXT, M_LEFT, FOOTER_Y);
  // Right: page number
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - M_RIGHT, FOOTER_Y, { align: "right" });
  // Top rule
  doc.setDrawColor(220, 220, 230);
  doc.setLineWidth(0.3);
  doc.line(M_LEFT, FOOTER_Y - 4, PAGE_W - M_RIGHT, FOOTER_Y - 4);
}

function checkPage(doc: jsPDF, y: number, needed: number = 20): number {
  if (y + needed > FOOTER_Y - 10) {
    doc.addPage();
    return M_TOP;
  }
  return y;
}

function sectionHeading(doc: jsPDF, text: string, y: number): number {
  y = checkPage(doc, y, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...BRAND_BLUE);
  doc.text(text.toUpperCase(), M_LEFT, y);
  y += 2;
  doc.setDrawColor(...BRAND_BLUE);
  doc.setLineWidth(0.8);
  doc.line(M_LEFT, y, M_LEFT + 40, y);
  return y + 8;
}

function riskColor(tag: string): readonly [number, number, number] {
  const t = (tag || "").toLowerCase();
  if (t.includes("high") || t.includes("critical")) return RISK_HIGH;
  if (t.includes("medium") || t.includes("moderate")) return RISK_MEDIUM;
  return RISK_LOW;
}

export function downloadPDF(agentName: string, result: Record<string, any>) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  // ─── PAGE 1: Cover ───
  // Full navy background
  doc.setFillColor(...BRAND_NAVY);
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");

  // Accent stripe
  doc.setFillColor(...BRAND_BLUE);
  doc.rect(0, 0, 6, PAGE_H, "F");

  // Title block
  doc.setFont("helvetica", "bold");
  doc.setFontSize(32);
  doc.setTextColor(...WHITE);
  const titleLines = doc.splitTextToSize(agentName, CONTENT_W - 10);
  let ty = 100;
  titleLines.forEach((line: string) => {
    doc.text(line, M_LEFT + 8, ty);
    ty += 14;
  });

  // Subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(14);
  doc.setTextColor(180, 190, 210);
  doc.text("Decision Intelligence Report", M_LEFT + 8, ty + 6);

  // Date
  doc.setFontSize(11);
  doc.setTextColor(140, 150, 170);
  doc.text(dateStr, M_LEFT + 8, ty + 18);

  // Context line
  if (result.contextLine) {
    doc.setFontSize(10);
    doc.setTextColor(160, 170, 190);
    const ctxLines = doc.splitTextToSize(result.contextLine, CONTENT_W - 20);
    doc.text(ctxLines, M_LEFT + 8, ty + 30);
  }

  // Footer on cover
  doc.setFontSize(9);
  doc.setTextColor(100, 110, 130);
  doc.text("Powered by unfoldHR AI", M_LEFT + 8, PAGE_H - 30);
  doc.setFontSize(7.5);
  doc.setTextColor(80, 90, 110);
  doc.text("www.unfoldhrai.com", M_LEFT + 8, PAGE_H - 22);

  // ─── CONTENT PAGES ───
  doc.addPage();
  let y = M_TOP;

  // ── Summary ──
  if (result.summary) {
    y = sectionHeading(doc, "Executive Summary", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(...TEXT_PRIMARY);
    const summaryLines = doc.splitTextToSize(result.summary, CONTENT_W);
    summaryLines.forEach((line: string) => {
      y = checkPage(doc, y, 6);
      doc.text(line, M_LEFT, y);
      y += 5.5;
    });
    y += 8;
  }

  // ── Confidence Score ──
  if (result.confidence) {
    y = checkPage(doc, y, 35);
    // Box
    doc.setFillColor(...LIGHT_GRAY);
    doc.roundedRect(M_LEFT, y - 4, CONTENT_W, 28, 3, 3, "F");

    const conf = result.confidence;
    const scoreColor = conf.score >= 75 ? BRAND_TEAL : conf.score >= 60 ? RISK_MEDIUM : RISK_HIGH;

    // Score circle
    const cx = M_LEFT + 18;
    const cy2 = y + 10;
    doc.setFillColor(...scoreColor);
    doc.circle(cx, cy2, 10, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...WHITE);
    doc.text(`${conf.score}%`, cx, cy2 + 1.5, { align: "center" });

    // Label
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(...TEXT_PRIMARY);
    doc.text(`Confidence: ${conf.level}`, M_LEFT + 34, y + 7);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(...TEXT_SECONDARY);
    const reasonLines = doc.splitTextToSize(conf.reason, CONTENT_W - 42);
    doc.text(reasonLines, M_LEFT + 34, y + 14);

    y += 34;
  }

  // ── Sections (Key Themes, Recommendations, etc.) ──
  (result.sections || []).forEach((sec: any) => {
    y = sectionHeading(doc, sec.title, y);

    (sec.items || []).forEach((item: any) => {
      y = checkPage(doc, y, 16);

      // Tag pill
      if (item.tag) {
        const tagCol = riskColor(item.tag);
        const tagW = doc.getTextWidth(item.tag) + 6;
        doc.setFillColor(...tagCol);
        doc.roundedRect(M_LEFT, y - 3.5, tagW + 2, 5.5, 1.5, 1.5, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7);
        doc.setTextColor(...WHITE);
        doc.text(item.tag.toUpperCase(), M_LEFT + 3, y);
        y += 5;
      }

      // Label
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...TEXT_PRIMARY);
      doc.text(`•  ${item.label}`, M_LEFT + 2, y);
      y += 5;

      // Detail
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(...TEXT_SECONDARY);
      const detailLines = doc.splitTextToSize(item.detail, CONTENT_W - 12);
      detailLines.forEach((line: string) => {
        y = checkPage(doc, y, 5);
        doc.text(line, M_LEFT + 8, y);
        y += 4.8;
      });
      y += 4;
    });
    y += 4;
  });

  // ── Timeline ──
  if (result.timeline?.length) {
    y = sectionHeading(doc, "Implementation Timeline", y);

    // Table header
    y = checkPage(doc, y, 12);
    doc.setFillColor(...BRAND_NAVY);
    doc.roundedRect(M_LEFT, y - 4, CONTENT_W, 8, 1.5, 1.5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(...WHITE);
    doc.text("PHASE", M_LEFT + 4, y);
    doc.text("FOCUS", M_LEFT + 55, y);
    doc.text("WEIGHT", PAGE_W - M_RIGHT - 4, y, { align: "right" });
    y += 8;

    result.timeline.forEach((t: any, i: number) => {
      y = checkPage(doc, y, 10);
      if (i % 2 === 0) {
        doc.setFillColor(248, 248, 252);
        doc.rect(M_LEFT, y - 4, CONTENT_W, 9, "F");
      }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...TEXT_PRIMARY);
      doc.text(t.phase, M_LEFT + 4, y);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(...TEXT_SECONDARY);
      const focusLines = doc.splitTextToSize(t.focus, 80);
      doc.text(focusLines[0], M_LEFT + 55, y);

      // Progress bar
      const barX = PAGE_W - M_RIGHT - 30;
      const barW = 22;
      doc.setFillColor(230, 230, 240);
      doc.roundedRect(barX, y - 2.5, barW, 4, 1, 1, "F");
      doc.setFillColor(...BRAND_BLUE);
      doc.roundedRect(barX, y - 2.5, barW * (t.pct / 100), 4, 1, 1, "F");
      doc.setFontSize(7.5);
      doc.setTextColor(...TEXT_PRIMARY);
      doc.text(`${t.pct}%`, PAGE_W - M_RIGHT - 2, y, { align: "right" });

      y += 10;
    });
    y += 6;
  }

  // ── Risks ──
  if (result.risks?.length) {
    y = sectionHeading(doc, "Risks & Observations", y);

    result.risks.forEach((r: string) => {
      y = checkPage(doc, y, 14);

      // Risk card
      doc.setFillColor(255, 250, 245);
      doc.setDrawColor(240, 200, 160);
      doc.setLineWidth(0.3);
      doc.roundedRect(M_LEFT, y - 4, CONTENT_W, 11, 2, 2, "FD");

      // Warning icon
      doc.setFillColor(234, 179, 8);
      doc.circle(M_LEFT + 7, y + 1.5, 2.5, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(...WHITE);
      doc.text("!", M_LEFT + 7, y + 2.5, { align: "center" });

      // Text
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(...TEXT_PRIMARY);
      const riskLines = doc.splitTextToSize(r, CONTENT_W - 20);
      doc.text(riskLines[0], M_LEFT + 14, y + 2);
      y += 14;
    });
    y += 4;
  }

  // ── Add footers to all pages ──
  const totalPages = doc.getNumberOfPages();
  for (let i = 2; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i - 1, totalPages - 1);
  }

  doc.save(`${agentName.replace(/\s+/g, "_")}_Report.pdf`);
}
