import jsPDF from "jspdf";
import { sanitizeResult, qualitativeConfidence } from "@/lib/sanitizeAgentOutput";

/* ─── Result shape ───
 * Agent results arrive as free-form JSON, so they are narrowed once, up front,
 * into the shape the CSV and PDF renderers actually read.
 */

interface ResultItem {
  label?: string;
  detail?: string;
  tag?: string;
}

interface ResultSection {
  title?: string;
  items?: ResultItem[];
}

interface ResultPhase {
  phase?: string;
  focus?: string;
  pct?: number;
}

interface ResultConfidence {
  level?: string;
  score?: number;
  reason?: string;
}

interface NormalizedResult {
  contextLine?: string;
  summary?: string;
  sections?: ResultSection[];
  timeline?: ResultPhase[];
  risks?: string[];
  confidence?: ResultConfidence;
  [key: string]: unknown;
}

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null && !Array.isArray(v);

const asString = (v: unknown): string | undefined =>
  typeof v === "string" ? v : typeof v === "number" || typeof v === "boolean" ? String(v) : undefined;

const asNumber = (v: unknown): number | undefined => (typeof v === "number" ? v : undefined);

function normalizeResult(source: object): NormalizedResult {
  // Copy into an index-accessible record without assertions, so typed callers
  // (interfaces without index signatures) work too.
  const result: Record<string, unknown> = Object.fromEntries(Object.entries(source));
  const out: NormalizedResult = { ...result };

  out.contextLine = asString(result.contextLine);
  out.summary = asString(result.summary);

  if (Array.isArray(result.sections)) {
    out.sections = result.sections.map((sec) => {
      const s = isRecord(sec) ? sec : {};
      return {
        title: asString(s.title),
        items: Array.isArray(s.items)
          ? s.items.map((item) => {
              const it = isRecord(item) ? item : {};
              return { label: asString(it.label), detail: asString(it.detail), tag: asString(it.tag) };
            })
          : [],
      };
    });
  } else {
    out.sections = [];
  }

  if (Array.isArray(result.timeline)) {
    out.timeline = result.timeline.map((entry) => {
      const t = isRecord(entry) ? entry : {};
      return { phase: asString(t.phase), focus: asString(t.focus), pct: asNumber(t.pct) };
    });
  } else {
    out.timeline = [];
  }

  // Non-string risks were already discarded downstream; keep that behavior.
  out.risks = Array.isArray(result.risks)
    ? result.risks.filter((r): r is string => typeof r === "string")
    : [];

  if (result.confidence) {
    const c = isRecord(result.confidence) ? result.confidence : {};
    out.confidence = { level: asString(c.level), score: asNumber(c.score), reason: asString(c.reason) };
  } else {
    out.confidence = undefined;
  }

  return out;
}

/* ─── CSV Export ─── */
export function downloadCSV(
  agentName: string,
  result: object,
  inputs: unknown = {},
) {
  const safe = sanitizeResult(normalizeResult(result), inputs);
  const rows: string[][] = [["Section", "Label", "Detail", "Tag"]];

  if (safe.summary) {
    rows.push(["Summary", safe.summary, "", ""]);
  }

  (safe.sections || []).forEach((sec) => {
    (sec.items || []).forEach((item) => {
      rows.push([String(sec.title), String(item.label), String(item.detail), item.tag || ""]);
    });
  });

  (safe.timeline || []).forEach((t) => {
    rows.push(["Timeline", String(t.phase), String(t.focus), ""]);
  });

  (safe.risks || []).forEach((r: string, i: number) => {
    rows.push(["Risks", `Risk ${i + 1}`, r, ""]);
  });

  if (safe.confidence) {
    const q = qualitativeConfidence(safe.confidence.level, safe.confidence.score);
    rows.push(["Confidence", q.level, safe.confidence.reason || "", ""]);
  }

  const csv = rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${agentName.replace(/\s+/g, "_")}_result.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

/* ─── Branded PDF Export via jsPDF ─── */

type RGB = [number, number, number];
const BRAND_NAVY: RGB = [28, 35, 48];
const BRAND_BLUE: RGB = [43, 92, 230];
const BRAND_TEAL: RGB = [16, 185, 129];
const WHITE: RGB = [255, 255, 255];
const LIGHT_GRAY: RGB = [245, 245, 250];
const TEXT_PRIMARY: RGB = [30, 30, 40];
const TEXT_SECONDARY: RGB = [100, 100, 115];
const RISK_HIGH: RGB = [220, 38, 38];
const RISK_MEDIUM: RGB = [234, 179, 8];
const RISK_LOW: RGB = [34, 197, 94];

const PAGE_W = 210;
const PAGE_H = 297;
const M_LEFT = 24;
const M_RIGHT = 24;
const M_TOP = 28;
const CONTENT_W = PAGE_W - M_LEFT - M_RIGHT;
const FOOTER_Y = PAGE_H - 14;
const FOOTER_TEXT = "Generated by unfoldHR  •  www.unfoldhrai.com  •  Confidential";

function addFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  doc.setFontSize(7.5);
  doc.setTextColor(...TEXT_SECONDARY);
  doc.setFont("helvetica", "normal");
  doc.text(FOOTER_TEXT, M_LEFT, FOOTER_Y);
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - M_RIGHT, FOOTER_Y, { align: "right" });
  doc.setDrawColor(220, 220, 230);
  doc.setLineWidth(0.3);
  doc.line(M_LEFT, FOOTER_Y - 4, PAGE_W - M_RIGHT, FOOTER_Y - 4);
}

function checkPage(doc: jsPDF, y: number, needed: number = 20): number {
  if (y + needed > FOOTER_Y - 10) {
    doc.addPage();
    return M_TOP;
  }
  return y;
}

function sectionHeading(doc: jsPDF, text: string, y: number): number {
  y = checkPage(doc, y, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...BRAND_BLUE);
  doc.text(text.toUpperCase(), M_LEFT, y);
  y += 2;
  doc.setDrawColor(...BRAND_BLUE);
  doc.setLineWidth(0.8);
  doc.line(M_LEFT, y, M_LEFT + 40, y);
  return y + 8;
}

function riskColor(tag: string): RGB {
  const t = (tag || "").toLowerCase();
  if (t.includes("high") || t.includes("critical")) return RISK_HIGH;
  if (t.includes("medium") || t.includes("moderate")) return RISK_MEDIUM;
  return RISK_LOW;
}

export function downloadPDF(agentName: string, result: object, inputs: unknown = {}) {
  const safe = sanitizeResult(normalizeResult(result), inputs);
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  // ─── PAGE 1: Cover ───
  doc.setFillColor(...BRAND_NAVY);
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");
  doc.setFillColor(...BRAND_BLUE);
  doc.rect(0, 0, 6, PAGE_H, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(32);
  doc.setTextColor(...WHITE);
  const titleLines = doc.splitTextToSize(agentName, CONTENT_W - 10);
  let ty = 100;
  titleLines.forEach((line: string) => {
    doc.text(line, M_LEFT + 8, ty);
    ty += 14;
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(14);
  doc.setTextColor(180, 190, 210);
  doc.text("Decision Intelligence Report", M_LEFT + 8, ty + 6);

  doc.setFontSize(11);
  doc.setTextColor(140, 150, 170);
  doc.text(dateStr, M_LEFT + 8, ty + 18);

  if (safe.contextLine) {
    doc.setFontSize(10);
    doc.setTextColor(160, 170, 190);
    const ctxLines = doc.splitTextToSize(safe.contextLine, CONTENT_W - 20);
    doc.text(ctxLines, M_LEFT + 8, ty + 30);
  }

  doc.setFontSize(9);
  doc.setTextColor(100, 110, 130);
  doc.text("Powered by unfoldHR AI", M_LEFT + 8, PAGE_H - 30);
  doc.setFontSize(7.5);
  doc.setTextColor(80, 90, 110);
  doc.text("www.unfoldhrai.com", M_LEFT + 8, PAGE_H - 22);

  // ─── CONTENT PAGES ───
  doc.addPage();
  let y = M_TOP;

  if (safe.summary) {
    y = sectionHeading(doc, "Executive Summary", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(...TEXT_PRIMARY);
    const summaryLines = doc.splitTextToSize(safe.summary, CONTENT_W);
    summaryLines.forEach((line: string) => {
      y = checkPage(doc, y, 6);
      doc.text(line, M_LEFT, y);
      y += 5.5;
    });
    y += 8;
  }

  // ── Confidence (qualitative only — no numeric score) ──
  if (safe.confidence) {
    y = checkPage(doc, y, 35);
    doc.setFillColor(...LIGHT_GRAY);
    doc.roundedRect(M_LEFT, y - 4, CONTENT_W, 28, 3, 3, "F");

    const q = qualitativeConfidence(safe.confidence.level, safe.confidence.score);
    const scoreColor = q.level === "High" ? BRAND_TEAL : q.level === "Medium" ? RISK_MEDIUM : RISK_HIGH;

    const cx = M_LEFT + 18;
    const cy2 = y + 10;
    doc.setFillColor(...scoreColor);
    doc.circle(cx, cy2, 10, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(...WHITE);
    doc.text(q.initial, cx, cy2 + 2, { align: "center" });

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(...TEXT_PRIMARY);
    doc.text(`${q.level} Confidence`, M_LEFT + 34, y + 7);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(...TEXT_SECONDARY);
    if (safe.confidence.reason) {
      const reasonLines = doc.splitTextToSize(safe.confidence.reason, CONTENT_W - 42);
      doc.text(reasonLines, M_LEFT + 34, y + 14);
    }

    y += 34;
  }

  (safe.sections || []).forEach((sec) => {
    y = sectionHeading(doc, String(sec.title), y);

    (sec.items || []).forEach((item) => {
      y = checkPage(doc, y, 16);

      if (item.tag) {
        const tagCol = riskColor(item.tag);
        const tagW = doc.getTextWidth(item.tag) + 6;
        doc.setFillColor(...tagCol);
        doc.roundedRect(M_LEFT, y - 3.5, tagW + 2, 5.5, 1.5, 1.5, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7);
        doc.setTextColor(...WHITE);
        doc.text(item.tag.toUpperCase(), M_LEFT + 3, y);
        y += 5;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...TEXT_PRIMARY);
      doc.text(`•  ${item.label}`, M_LEFT + 2, y);
      y += 5;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(...TEXT_SECONDARY);
      const detailLines = doc.splitTextToSize(String(item.detail), CONTENT_W - 12);
      detailLines.forEach((line: string) => {
        y = checkPage(doc, y, 5);
        doc.text(line, M_LEFT + 8, y);
        y += 4.8;
      });
      y += 4;
    });
    y += 4;
  });

  // ── Timeline (qualitative phases — no pct labels) ──
  if (safe.timeline?.length) {
    y = sectionHeading(doc, "Implementation Phases", y);

    y = checkPage(doc, y, 12);
    doc.setFillColor(...BRAND_NAVY);
    doc.roundedRect(M_LEFT, y - 4, CONTENT_W, 8, 1.5, 1.5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(...WHITE);
    doc.text("PHASE", M_LEFT + 4, y);
    doc.text("FOCUS", M_LEFT + 55, y);
    y += 8;

    const equalPct = 100 / safe.timeline.length;
    safe.timeline.forEach((t, i: number) => {
      y = checkPage(doc, y, 10);
      if (i % 2 === 0) {
        doc.setFillColor(248, 248, 252);
        doc.rect(M_LEFT, y - 4, CONTENT_W, 9, "F");
      }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...TEXT_PRIMARY);
      // A timeline entry without a phase label previously threw inside jsPDF
      // ("Invalid arguments passed to jsPDF.text") and produced no PDF at all.
      doc.text(t.phase || "", M_LEFT + 4, y);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(...TEXT_SECONDARY);
      const focusLines = doc.splitTextToSize(t.focus || "", 80);
      doc.text(focusLines[0] || "", M_LEFT + 55, y);

      // Equal-share visual progress (no % label)
      const barX = PAGE_W - M_RIGHT - 30;
      const barW = 28;
      doc.setFillColor(230, 230, 240);
      doc.roundedRect(barX, y - 2.5, barW, 4, 1, 1, "F");
      doc.setFillColor(...BRAND_BLUE);
      doc.roundedRect(barX, y - 2.5, barW * (equalPct / 100), 4, 1, 1, "F");

      y += 10;
    });
    y += 6;
  }

  if (safe.risks?.length) {
    y = sectionHeading(doc, "Risks & Observations", y);

    safe.risks.forEach((r: string) => {
      y = checkPage(doc, y, 14);

      doc.setFillColor(255, 250, 245);
      doc.setDrawColor(240, 200, 160);
      doc.setLineWidth(0.3);
      doc.roundedRect(M_LEFT, y - 4, CONTENT_W, 11, 2, 2, "FD");

      doc.setFillColor(234, 179, 8);
      doc.circle(M_LEFT + 7, y + 1.5, 2.5, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(...WHITE);
      doc.text("!", M_LEFT + 7, y + 2.5, { align: "center" });

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(...TEXT_PRIMARY);
      const riskLines = doc.splitTextToSize(r, CONTENT_W - 20);
      doc.text(riskLines[0], M_LEFT + 14, y + 2);
      y += 14;
    });
    y += 4;
  }

  const totalPages = doc.getNumberOfPages();
  for (let i = 2; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i - 1, totalPages - 1);
  }

  doc.save(`${agentName.replace(/\s+/g, "_")}_Report.pdf`);
}
